GET http://localhost:8800/ebook/list
Accept: application/json

###

GET http://localhost:8800/ebook/list?name=教程
Accept: application/json

###

GET http://localhost:8800/ebook
Accept: application/json